Add disconnection from connected devices
ckrinitsin/bluetoothctl-dmenu pull request #1
Opened 2024-04-19 13:44 UTC by noahpy

Dear Mr. Krinitsin,
I have been a poweruser of this script from day one!
But, I really really would appreciate the additional feature of disconnecting from already connected devices, especially if I want to connect them with other endpoints.
I wrote this feature carefully and with love, I hope you could consider my small belittled contribution to become part of your prestigious, high regarded repository. 
This would shine a new, bright light into my world that I never fathomed to see.
So could you consider to accept this pull request on the repository of thee.
Then we shall enjoy our success with a sweet cup of tee.
Let our hearts grow thogether like a blossoming cherry tree.

Best regards;
Noah Schlenker

2024-04-19 13:44 UTC, noahpy commented
Pls

2024-04-20 15:00 UTC, 4rneee reviewed
Just small codestyle preferences.  
Otherwise LGTM!

2024-04-20 15:00 UTC, 4rneee commented on bluetooth-devices.sh
> +fi
I think for readability an else branch would be better instead of exiting early but I am open for discussion.

2024-04-20 15:00 UTC, 4rneee commented on bluetooth-devices.sh
> +if echo $CONNECTED | grep $DEVICE; then
Please be consistent with the other if statements and put the `then` in a new line.

2024-04-21 17:58 UTC, 4rneee requested changes
just very small things again

2024-04-21 17:58 UTC, 4rneee commented on bluetooth-devices.sh
> +connect_bluetooth(){
```suggestion
connect_bluetooth() {
```

2024-04-21 17:58 UTC, 4rneee commented on bluetooth-devices.sh
> +disconnect_bluetooth(){
```suggestion
disconnect_bluetooth() {
```

2024-04-21 17:58 UTC, 4rneee commented on bluetooth-devices.sh
>  # Opens dmenu prompt, which lets you decide which device you want to connect to
```suggestion
# Opens dmenu prompt, which lets you decide which device you want to connect/disconnect to
```

2024-04-21 18:50 UTC, 4rneee approved these changes
:+1:

2024-04-22 09:19 UTC, merged